### ISSUE TITLE
change to mariadb connector/node.js

### ISSUE THREAD

**Issue by victor0801x** [fastify/fastify-mysql#15]
as titile, when [mariadb offical node.js connector](https://github.com/MariaDB/mariadb-connector-nodejs) stable release
- support both Promise/callback API.
- compatible with `mysql` & `mysql2`
- new features. insert streaming, pipeling
- more performant
...

**Comment by mcollina** [comment]
would you like to send a PR?

**Comment by victor0801x** [comment]
I'll try this weekend
