### ISSUE TITLE
connect to multiple databases

### ISSUE THREAD

**Issue by ksonho** [fastify/fastify-mysql#19]
I am trying to register the plugin to two different databases. However it is not work due to the plugin only can be registered once. Any solution for that?

**Comment by niraj-gawande** [comment]
I am facing the same issue.  Have solved the problem?

**Comment by victor0801x** [comment]
1. can always specifiy the table belongs to which database. ex: `SELECT * FROM <db_name>.<table_name>`. or
2. can use syntax `USE db_name;` in your query. ex: `USE db_name; SELECT * FROM table_name;`
