### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by ksonho** [fastify/fastify-mysql#26]
my sql server version is 5.6.1

When I connect to the db, it works fine. However one day later (no connection and query has been done), when I query the db again, it got the error.

Error 1 on begin transaction: Error: This socket has been ended by the other party
Error 2 on commit: Error: Can't add new command when connection is in closed state

and here are my code
for the register
```
fastify.register(require('fastify-mysql'), {
	promise: true,
	host: config._mysql.host,
	user: config._mysql.user,
	password: config._mysql.pass,
	database: config._mysql.database,
	connectionLimit: 10,
	waitForConnections: true,
})
```

for the class favour to myself
```
class SQLPlugin {
	constructor(mysql) {
			this.mysql = mysql
	}
	async query(query, param) {
		console.log('query: ', query)
		console.log('param: ', param)
		const [rows, fields] = await this.connection.query(query, param)
		return rows
	}
	async beginTransaction() {
		console.log('begin')
		this.connection = await this.mysql.getConnection()
		await this.connection.beginTransaction()
	}
	async commit() {
		console.log('commit')
		await this.connection.commit()
		this.connection.release()
	}
	async rollback() {
		console.log('rollback')
		await this.connection.rollback()
		this.connection.release()
	}
}
```

**Comment by Eomm** [comment]
I think you have problem managing this.connection
(I don't see where it is assigned) but if the connection is closed, you should reconnect it

**Comment by ksonho** [comment]
> I think you have problem managing this.connection
> (I don't see where it is assigned) but if the connection is closed, you should reconnect it

this.connection is created on beginTransaction() which I used in onRequest hook. Every request I will get a connection to this.connection. 

I am wondering if the connections in the pool are disconnected due to timeout. if it is, how can I reconnect the whole sql pool?

**Comment by victor0801x** [comment]
in your class impl. I think if concurrency beginTransaction, the following will overwrite previouse. cause some connection may not release then reach connectionLimit or never commit thus server transaction timeout.

**Comment by victor0801x** [comment]
also, if connection disconnect in pool, just getConnection again, pool will handle reconnect or give u other available connection unless pool is closed. i.e. pool.end()
