### ISSUE TITLE
Big numbers (edit: plugin options)

### ISSUE THREAD

**Issue by LizroDev** [fastify/fastify-mysql#82]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,
During my queries, large numbers cause a problem: the last digits are replaced by 0. Is it possible to, like mysql2, configure the plugin like this? Normally resolving the problem.

```js
fastify.register(require('fastify-mysql'), {
  promise: true,
  supportBigNumbers: true,
  bigNumberStrings: true,
  connectionString: 'mysql://'+mysqlUser+':'+mysqlPassword+'@'+mysqlHost+':'+mysqlPort+'/'+mysqlDatabase
})
```

Thanks

**Comment by jsumners** [comment]
The readme states:

https://github.com/fastify/fastify-mysql/blob/1000fea47b53fe682786f6b59b30fb28b815ad8c/README.md?plain=1#L9

**Comment by LizroDev** [comment]
> The readme states:
> 
> https://github.com/fastify/fastify-mysql/blob/1000fea47b53fe682786f6b59b30fb28b815ad8c/README.md?plain=1#L9

This is not quite correct, after a bit of research in the source code I found the solution to my problem.

https://github.com/fastify/fastify-mysql/blob/1000fea47b53fe682786f6b59b30fb28b815ad8c/index.js#L67
If a connection String is used, the options are not passed to the pool builder.

Therefore, this works : 
```js
fastify.register(require('fastify-mysql'), {
  promise: true,
  host: mysqlHost,
  port: mysqlPort,
  database: mysqlDatabase,
  user: mysqlUser,
  password: mysqlPassword,
  supportBigNumbers: true,
  bigNumberStrings: true
})
```
but not this
```js
fastify.register(require('fastify-mysql'), {
  promise: true,
  supportBigNumbers: true,
  bigNumberStrings: true,
  connectionString: 'mysql://'+mysqlUser+':'+mysqlPassword+'@'+mysqlHost+':'+mysqlPort+'/'+mysqlDatabase
}) 
```

The sentence should be changed so as not to be confusing and to be more precise.
Have a good evening

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by LizroDev** [comment]
Of course, it's done !
