### ISSUE TITLE
Deprecation warning description in README.md in `fastify.listen`

### ISSUE THREAD

**Issue by phasetr** [fastify/fastify-mysql#96]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the newest README.md, we have a description `fastify.listen(3000, err => {`, but this leads a deprecation warning, like

>FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.

This should be `fastify.listen({ port: 3000 }, err => {`.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by phasetr** [comment]
The pull request is merged.
